-- =====================================================================================
-- Sunshine Academy — Teachers Attendance System
-- Supabase / PostgreSQL schema, security (RLS) and server-side logic
--
-- HOW TO USE: Supabase Dashboard -> SQL Editor -> New query -> paste this WHOLE file -> Run.
-- It is safe to run again (it uses "create if not exists" / "create or replace" / "drop ... if exists").
-- It never deletes any attendance data.
--
-- SECURITY MODEL (read this once):
--   * Row Level Security (RLS) is ON for every table. Browsers can only SELECT, and only the rows
--     their role may see (teacher = own rows only, admin = everything).
--   * Browsers have NO insert/update/delete privilege on any table. Every change goes through a
--     function below that checks "is this an active admin?" (or "is this the signed-in teacher?")
--     inside the database. Role and status are looked up live from the database on every call,
--     never taken from the browser or from user-editable token fields.
--   * Attendance has no delete function and no delete policy: history is permanent.
-- =====================================================================================

-- ---------- 0. Schemas ----------------------------------------------------------------
create schema if not exists private;          -- internal helpers; NOT exposed through the API
revoke all on schema private from public;

-- ---------- 1. Tables -----------------------------------------------------------------

-- 1.1 profiles: one row per login (Supabase Auth keeps the password; we never store one).
create table if not exists public.profiles (
  id            uuid primary key default gen_random_uuid(),
  auth_user_id  uuid not null unique references auth.users (id) on delete cascade,
  name          text not null check (char_length(name) between 2 and 80),
  email         text not null check (char_length(email) <= 120),
  role          text not null default 'teacher' check (role in ('admin', 'teacher')),
  status        text not null default 'pending' check (status in ('active', 'inactive', 'pending', 'rejected')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index if not exists profiles_email_key on public.profiles (lower(email));

-- 1.2 teachers: the academy's teacher records (Teacher IDs like T-001).
create table if not exists public.teachers (
  id             bigint generated by default as identity primary key,
  teacher_id     text not null check (teacher_id ~ '^[A-Z0-9-]{2,20}$'),
  name           text not null check (char_length(name) between 2 and 80),
  email          text not null check (char_length(email) <= 120 and email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  phone          text not null default '' check (phone = '' or phone ~ '^[0-9+()[:space:]-]{7,20}$'),
  subject        text not null default '' check (char_length(subject) <= 60),
  date_of_birth  date,
  joining_date   date not null,
  address        text not null default '' check (char_length(address) <= 200),
  status         text not null default 'pending' check (status in ('active', 'inactive', 'pending', 'rejected')),
  auth_user_id   uuid unique references auth.users (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint teachers_teacher_id_key unique (teacher_id)
);
create unique index if not exists teachers_email_key on public.teachers (lower(email));
create index if not exists teachers_status_idx on public.teachers (status);

-- 1.3 attendance: one row per teacher per day. Permanent: never deleted automatically.
create table if not exists public.attendance (
  id               bigint generated by default as identity primary key,
  teacher_id       bigint not null references public.teachers (id) on delete restrict,
  attendance_date  date not null,
  check_in         time,
  check_out        time,
  status           text not null check (status in ('present', 'absent', 'late', 'leave')),
  late_minutes     integer not null default 0 check (late_minutes >= 0),
  remarks          text not null default '' check (char_length(remarks) <= 200),
  created_by       uuid references auth.users (id) on delete set null,
  updated_by       uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint attendance_teacher_date_key unique (teacher_id, attendance_date),
  constraint attendance_times_in_order check (check_in is null or check_out is null or check_out > check_in),
  constraint attendance_no_times_when_off check (status not in ('absent', 'leave') or (check_in is null and check_out is null))
);
create index if not exists attendance_date_idx on public.attendance (attendance_date);

-- 1.4 settings: school start time, grace period, self check-in on/off, timezone, ...
create table if not exists public.settings (
  name        text primary key check (name in ('school_start', 'grace_minutes', 'self_checkin', 'timezone', 'max_pending', 'legacy_link')),
  value       text not null,
  updated_at  timestamptz not null default now(),
  updated_by  uuid
);

-- 1.5 audit_logs: append-only record of important admin actions.
create table if not exists public.audit_logs (
  id             bigint generated always as identity primary key,
  actor_user_id  uuid,
  action         text not null,
  entity_type    text not null,
  entity_id      text,
  old_data       jsonb,
  new_data       jsonb,
  created_at     timestamptz not null default now()
);
create index if not exists audit_logs_created_idx on public.audit_logs (created_at desc);

-- 1.6 One-time code that protects the "create the first administrator" step.
create table if not exists private.setup_secret (
  code        text primary key,
  created_at  timestamptz not null default now()
);

-- ---------- 2. Internal helper functions (schema "private") ---------------------------

create or replace function private.is_importing() returns boolean
language sql stable set search_path = '' as $$
  select coalesce(current_setting('app.importing', true), '') = 'on'
$$;

-- Read a setting (security definer: teachers can't read the settings table, but rules still apply to them).
create or replace function private.setting(p_name text, p_default text) returns text
language sql stable security definer set search_path = '' as $$
  select coalesce((select s.value
                     from public.settings s
                    where s.name = p_name
                    order by s.updated_at desc
                    limit 1), p_default)
$$;

create or replace function private.academy_tz() returns text
language sql stable security definer set search_path = '' as $$
  select coalesce(private.setting('timezone', 'Asia/Karachi'), 'Asia/Karachi')
$$;

-- The academy's own clock (default Asia/Karachi). Attendance dates/times come from HERE, never from the browser.
create or replace function private.academy_now() returns timestamp
language sql stable security definer set search_path = '' as $$
  select now() at time zone private.academy_tz()
$$;

create or replace function private.academy_today() returns date
language sql stable security definer set search_path = '' as $$
  select (now() at time zone private.academy_tz())::date
$$;

-- Is the signed-in user an ACTIVE admin? Looked up live in the database.
create or replace function private.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles p
    where p.auth_user_id = (select auth.uid()) and p.role = 'admin' and p.status = 'active'
  )
$$;

-- The signed-in user's teacher id, ONLY if they are an active teacher (otherwise NULL).
create or replace function private.current_teacher_id() returns bigint
language sql stable security definer set search_path = '' as $$
  select t.id from public.teachers t
  where t.auth_user_id = (select auth.uid()) and t.status = 'active'
  limit 1
$$;

create or replace function private.minutes_of(p_time time) returns integer
language sql immutable set search_path = '' as $$
  select (extract(hour from p_time) * 60 + extract(minute from p_time))::integer
$$;

-- Last minute (as minutes after midnight) that still counts as on time: start + grace, capped at 23:59.
create or replace function private.on_time_limit() returns integer
language sql stable security definer set search_path = '' as $$
  select least(
    private.minutes_of(private.setting('school_start', '08:00')::time) + coalesce(nullif(private.setting('grace_minutes', '15'), '')::integer, 15),
    23 * 60 + 59)
$$;

-- Raise a user-friendly error. PTnnn codes become HTTP status nnn in the API; hint = the form field to highlight.
create or replace function private.fail(p_status integer, p_message text, p_hint text default null) returns void
language plpgsql immutable set search_path = '' as $$
begin
  raise exception '%', p_message using errcode = 'PT' || p_status::text, hint = p_hint;
end $$;

-- Write an audit entry. Only definer functions/triggers call this; browsers cannot.
create or replace function private.audit(p_actor uuid, p_action text, p_entity text, p_entity_id text, p_old jsonb, p_new jsonb) returns void
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.audit_logs (actor_user_id, action, entity_type, entity_id, old_data, new_data)
  values (p_actor, p_action, p_entity, p_entity_id, p_old, p_new);
end $$;

-- Next free academy code: T-001, T-002 ...
create or replace function private.next_teacher_code() returns text
language plpgsql security definer set search_path = '' as $$
declare v_max integer;
begin
  perform pg_advisory_xact_lock(hashtext('sunshine_teacher_code'));
  select coalesce(max(substring(teacher_id from 3)::integer), 0) into v_max
  from public.teachers where teacher_id ~ '^T-[0-9]{1,9}$';
  return 'T-' || lpad((v_max + 1)::text, 3, '0');
end $$;

-- JSON shapes the existing frontend already understands ------------------------------
create or replace function private.teacher_json(t public.teachers) returns jsonb
language sql immutable set search_path = '' as $$
  select jsonb_build_object(
    'id', t.id, 'teacher_id', t.teacher_id, 'name', t.name, 'email', t.email, 'phone', t.phone,
    'subject', t.subject, 'date_of_birth', coalesce(to_char(t.date_of_birth, 'YYYY-MM-DD'), ''),
    'joining_date', to_char(t.joining_date, 'YYYY-MM-DD'), 'address', t.address, 'status', t.status,
    'created_at', t.created_at, 'updated_at', t.updated_at)
$$;

create or replace function private.att_json(a public.attendance, t public.teachers) returns jsonb
language sql immutable set search_path = '' as $$
  select jsonb_build_object(
    'id', a.id,
    'teacher', jsonb_build_object('id', t.id, 'teacher_id', t.teacher_id, 'name', t.name, 'subject', t.subject, 'status', t.status),
    'date', to_char(a.attendance_date, 'YYYY-MM-DD'),
    'check_in', coalesce(to_char(a.check_in, 'HH24:MI'), ''),
    'check_out', coalesce(to_char(a.check_out, 'HH24:MI'), ''),
    'status', a.status, 'late_minutes', a.late_minutes, 'remarks', a.remarks)
$$;

-- Attendance Percentage = Present days / Total working days x 100  (same rule as the old app)
create or replace function private.stats_json(p integer, a integer, l integer, v integer) returns jsonb
language sql immutable set search_path = '' as $$
  select jsonb_build_object(
    'totalDays', p + a + l + v, 'present', p, 'absent', a, 'late', l, 'leave', v,
    'percentage', case when p + a + l + v = 0 then 0 else round(p::numeric / (p + a + l + v) * 100, 1) end)
$$;

create or replace function private.rules_json() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'startTime', private.setting('school_start', '08:00'),
    'graceMinutes', coalesce(nullif(private.setting('grace_minutes', '15'), '')::integer, 15),
    'selfCheckin', private.setting('self_checkin', '1') = '1',
    'lateAfter', lpad((private.on_time_limit() / 60)::text, 2, '0') || ':' || lpad((private.on_time_limit() % 60)::text, 2, '0'),
    'timezone', private.academy_tz())
$$;

-- ---------- 3. Triggers ---------------------------------------------------------------

-- 3.1 Keep updated_at fresh
create or replace function private.set_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function private.set_updated_at();
drop trigger if exists teachers_set_updated_at on public.teachers;
create trigger teachers_set_updated_at before update on public.teachers for each row execute function private.set_updated_at();
drop trigger if exists attendance_set_updated_at on public.attendance;
create trigger attendance_set_updated_at before update on public.attendance for each row execute function private.set_updated_at();
drop trigger if exists settings_set_updated_at on public.settings;
create trigger settings_set_updated_at before update on public.settings for each row execute function private.set_updated_at();

-- 3.2 New sign-up (teacher registration, or an account created by the admin).
--     EVERY new account starts as a PENDING TEACHER. The role is NEVER read from anything the user sends.
create or replace function private.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  md        jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_email   text  := lower(trim(coalesce(new.email, '')));
  v_name    text  := left(trim(coalesce(md ->> 'name', '')), 80);
  v_phone   text  := trim(coalesce(md ->> 'phone', ''));
  v_subject text  := left(trim(coalesce(md ->> 'subject', '')), 60);
  v_address text  := left(trim(coalesce(md ->> 'address', '')), 200);
  v_dob     date  := nullif(trim(coalesce(md ->> 'date_of_birth', '')), '')::date;
  v_legacy  public.teachers;
  v_cap     integer;
begin
  if v_email = '' then
    raise exception 'An email address is required.' using errcode = 'PT400';
  end if;
  if char_length(v_name) < 2 then
    v_name := left(split_part(v_email, '@', 1), 80);
    if char_length(v_name) < 2 then v_name := 'New teacher'; end if;
  end if;
  if v_phone <> '' and v_phone !~ '^[0-9+()[:space:]-]{7,20}$' then
    raise exception 'Enter a valid phone number.' using errcode = 'PT400';
  end if;

  -- A teacher imported from the old MySQL system whose login has not been linked yet.
  select * into v_legacy from public.teachers t where lower(t.email) = v_email and t.auth_user_id is null for update;
  if found then
    if private.setting('legacy_link', '0') = '1' then
      -- Owner-controlled migration window: link the new login to the imported teacher record.
      update public.teachers set auth_user_id = new.id where id = v_legacy.id;
      insert into public.profiles (auth_user_id, name, email, role, status)
      values (new.id, v_legacy.name, v_email, 'teacher', v_legacy.status);
      perform private.audit(new.id, 'teacher_linked', 'teacher', v_legacy.id::text, null,
                            jsonb_build_object('teacher_code', v_legacy.teacher_id));
      return new;
    end if;
    raise exception 'This email address is reserved. Please contact the administrator.' using errcode = 'PT409';
  end if;

  -- Stop a flood of fake registrations.
  v_cap := coalesce(nullif(private.setting('max_pending', '25'), '')::integer, 25);
  if (select count(*) from public.teachers where status = 'pending') >= v_cap then
    raise exception 'Registrations are temporarily closed. Please contact the administrator.' using errcode = 'PT429';
  end if;

  insert into public.profiles (auth_user_id, name, email, role, status)
  values (new.id, v_name, v_email, 'teacher', 'pending');

  insert into public.teachers (teacher_id, name, email, phone, subject, date_of_birth, joining_date, address, status, auth_user_id)
  values (private.next_teacher_code(), v_name, v_email, v_phone, v_subject, v_dob, private.academy_today(), v_address, 'pending', new.id);

  perform private.audit(new.id, 'teacher_registered', 'teacher', null, null, jsonb_build_object('email_domain', split_part(v_email, '@', 2)));
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();

-- 3.3 A teacher's status/name is the source of truth; mirror it to profiles.
create or replace function private.teachers_sync_profile() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.auth_user_id is not null then
    update public.profiles set status = new.status, name = new.name where auth_user_id = new.auth_user_id and role = 'teacher';
  end if;
  return new;
end $$;
drop trigger if exists teachers_sync_profile on public.teachers;
create trigger teachers_sync_profile after update of status, name on public.teachers
  for each row when (old.status is distinct from new.status or old.name is distinct from new.name)
  execute function private.teachers_sync_profile();

-- 3.4 Roles can only change through the setup/admin functions below.
create or replace function private.profiles_guard() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.role is distinct from old.role and coalesce(current_setting('app.role_change', true), '') <> 'allowed' then
    raise exception 'Roles can only be changed through the setup function.' using errcode = 'PT403';
  end if;
  if new.auth_user_id is distinct from old.auth_user_id then
    raise exception 'A profile cannot be moved to another login.' using errcode = 'PT403';
  end if;
  return new;
end $$;
drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard before update on public.profiles for each row execute function private.profiles_guard();

-- 3.5 Audit: teacher changes (approve / reject / activate / deactivate / edits). Sensitive values are NOT copied.
create or replace function private.teachers_audit() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_action text;
  v_old jsonb := '{}'::jsonb;
  v_new jsonb := '{}'::jsonb;
  v_sens text[] := '{}';
begin
  if private.is_importing() then return new; end if;

  if new.status is distinct from old.status then
    v_action := case
      when old.status = 'pending' and new.status = 'active'   then 'teacher_approved'
      when new.status = 'rejected'                            then 'teacher_rejected'
      when new.status = 'active'                              then 'teacher_activated'
      when new.status = 'inactive'                            then 'teacher_deactivated'
      else 'teacher_status_changed' end;
    v_old := v_old || jsonb_build_object('status', old.status);
    v_new := v_new || jsonb_build_object('status', new.status);
  end if;
  if new.name is distinct from old.name then v_old := v_old || jsonb_build_object('name', old.name); v_new := v_new || jsonb_build_object('name', new.name); end if;
  if new.teacher_id is distinct from old.teacher_id then v_old := v_old || jsonb_build_object('teacher_id', old.teacher_id); v_new := v_new || jsonb_build_object('teacher_id', new.teacher_id); end if;
  if new.subject is distinct from old.subject then v_old := v_old || jsonb_build_object('subject', old.subject); v_new := v_new || jsonb_build_object('subject', new.subject); end if;
  if new.joining_date is distinct from old.joining_date then v_old := v_old || jsonb_build_object('joining_date', old.joining_date); v_new := v_new || jsonb_build_object('joining_date', new.joining_date); end if;
  if new.phone is distinct from old.phone then v_sens := array_append(v_sens, 'phone'); end if;
  if new.address is distinct from old.address then v_sens := array_append(v_sens, 'address'); end if;
  if new.date_of_birth is distinct from old.date_of_birth then v_sens := array_append(v_sens, 'date_of_birth'); end if;

  if v_new = '{}'::jsonb and cardinality(v_sens) = 0 then return new; end if;
  if cardinality(v_sens) > 0 then v_new := v_new || jsonb_build_object('sensitive_fields_changed', to_jsonb(v_sens)); end if;
  perform private.audit((select auth.uid()), coalesce(v_action, 'teacher_updated'), 'teacher', new.id::text, v_old, v_new);
  return new;
end $$;
drop trigger if exists teachers_audit on public.teachers;
create trigger teachers_audit after update on public.teachers for each row execute function private.teachers_audit();

-- 3.6 Attendance rules enforced by the database itself (not just by JavaScript)
create or replace function private.attendance_before_write() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_start time;
begin
  if tg_op = 'UPDATE' and (new.teacher_id <> old.teacher_id or new.attendance_date <> old.attendance_date) then
    raise exception 'The teacher and date of an attendance record cannot be changed.' using errcode = 'PT400';
  end if;
  if not private.is_importing() and new.attendance_date > private.academy_today() then
    raise exception 'You cannot record attendance for a future date.' using errcode = 'PT400', hint = 'date';
  end if;

  -- Late minutes = minutes after the school start time (0 for any other status)
  if new.status = 'late' and new.check_in is not null then
    v_start := private.setting('school_start', '08:00')::time;
    new.late_minutes := greatest(0, private.minutes_of(new.check_in) - private.minutes_of(v_start));
  else
    new.late_minutes := 0;
  end if;

  new.updated_by := coalesce((select auth.uid()), new.updated_by);
  if tg_op = 'INSERT' then new.created_by := coalesce(new.created_by, (select auth.uid())); end if;
  return new;
end $$;
drop trigger if exists attendance_before_write on public.attendance;
create trigger attendance_before_write before insert or update on public.attendance for each row execute function private.attendance_before_write();

-- Any delete (even by the project owner in the SQL editor) leaves a permanent trace.
create or replace function private.attendance_audit_delete() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform private.audit((select auth.uid()), 'attendance_deleted', 'attendance', old.id::text,
    jsonb_build_object('teacher_id', old.teacher_id, 'date', old.attendance_date, 'status', old.status,
                       'check_in', old.check_in, 'check_out', old.check_out, 'remarks', old.remarks), null);
  return old;
end $$;
drop trigger if exists attendance_audit_delete on public.attendance;
create trigger attendance_audit_delete before delete on public.attendance for each row execute function private.attendance_audit_delete();

-- 3.7 Settings must be valid; changes are audited
create or replace function private.settings_validate() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.name = 'school_start' and new.value !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then
    raise exception 'School start time must look like 08:00.' using errcode = 'PT400', hint = 'startTime';
  elsif new.name = 'grace_minutes' and (new.value !~ '^[0-9]{1,3}$' or new.value::integer > 120) then
    raise exception 'Grace period must be a whole number of minutes (0-120).' using errcode = 'PT400', hint = 'graceMinutes';
  elsif new.name in ('self_checkin', 'legacy_link') and new.value not in ('0', '1') then
    raise exception 'That setting must be 0 or 1.' using errcode = 'PT400';
  elsif new.name = 'max_pending' and (new.value !~ '^[0-9]{1,3}$' or new.value::integer < 1) then
    raise exception 'max_pending must be a number from 1 to 999.' using errcode = 'PT400';
  elsif new.name = 'timezone' and not exists (select 1 from pg_catalog.pg_timezone_names z where z.name = new.value) then
    raise exception 'Unknown timezone.' using errcode = 'PT400';
  end if;
  return new;
end $$;
drop trigger if exists settings_validate on public.settings;
create trigger settings_validate before insert or update on public.settings for each row execute function private.settings_validate();

create or replace function private.settings_audit() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.value is distinct from old.value and not private.is_importing() then
    perform private.audit((select auth.uid()), 'settings_changed', 'setting', new.name,
                          jsonb_build_object('value', old.value), jsonb_build_object('value', new.value));
  end if;
  return new;
end $$;
drop trigger if exists settings_audit on public.settings;
create trigger settings_audit after update on public.settings for each row execute function private.settings_audit();

-- 3.8 The audit log can only grow
create or replace function private.audit_logs_append_only() returns trigger
language plpgsql set search_path = '' as $$
begin
  raise exception 'The audit log is append-only.' using errcode = 'PT403';
end $$;
drop trigger if exists audit_logs_append_only on public.audit_logs;
create trigger audit_logs_append_only before update or delete on public.audit_logs for each row execute function private.audit_logs_append_only();

-- ---------- 4. Row Level Security -----------------------------------------------------
alter table public.profiles   enable row level security;
alter table public.teachers   enable row level security;
alter table public.attendance enable row level security;
alter table public.settings   enable row level security;
alter table public.audit_logs enable row level security;
alter table private.setup_secret enable row level security;   -- no policy at all: nobody but the owner can read it

-- Browsers may only READ. There are deliberately NO insert/update/delete policies:
-- all changes go through the audited functions in section 5.
drop policy if exists profiles_select   on public.profiles;
drop policy if exists teachers_select   on public.teachers;
drop policy if exists attendance_select on public.attendance;
drop policy if exists settings_select   on public.settings;
drop policy if exists audit_select      on public.audit_logs;

create policy profiles_select on public.profiles for select to authenticated
  using (auth_user_id = (select auth.uid()) or (select private.is_admin()));

create policy teachers_select on public.teachers for select to authenticated
  using (auth_user_id = (select auth.uid()) or (select private.is_admin()));

-- Teachers: only THEIR OWN attendance, and only while their account is active. Admin: everything.
create policy attendance_select on public.attendance for select to authenticated
  using ((select private.is_admin()) or teacher_id = (select private.current_teacher_id()));

create policy settings_select on public.settings for select to authenticated
  using ((select private.is_admin()));

create policy audit_select on public.audit_logs for select to authenticated
  using ((select private.is_admin()));

-- ---------- 4b. Privileges: least privilege --------------------------------------------
revoke all on all tables    in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant select on public.profiles, public.teachers, public.attendance, public.settings, public.audit_logs to authenticated;
grant usage on schema private to authenticated;
revoke all on all tables in schema private from public, anon, authenticated;

-- ---------- 5. Functions the app calls (RPC) -------------------------------------------
-- Reading functions run as the CALLER (so RLS applies). Writing functions run with the
-- database owner's rights, but each one checks who is calling before doing anything.

-- 5.1 Account / first-time setup ----------------------------------------------------------

-- Is the very first administrator still missing? (safe to expose: reveals nothing else)
create or replace function public.needs_setup() returns boolean
language sql stable security definer set search_path = '' as $$
  select not exists (select 1 from public.profiles where role = 'admin')
$$;

-- Lets the setup page reject a wrong code BEFORE it creates an account.
create or replace function public.verify_setup_code(p_code text) returns boolean
language sql stable security definer set search_path = '' as $$
  select not exists (select 1 from public.profiles where role = 'admin')
     and exists (select 1 from private.setup_secret s where s.code = coalesce(p_code, ''))
$$;

-- Who am I? Role and status come from the database, never from the browser.
create or replace function public.my_account() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_uid uuid := (select auth.uid());
  r record;
begin
  if v_uid is null then return null; end if;
  select p.name, p.email, p.role, p.status as pstatus, t.id as tid, t.teacher_id as tcode, t.status as tstatus
    into r
    from public.profiles p left join public.teachers t on t.auth_user_id = p.auth_user_id
   where p.auth_user_id = v_uid;
  if not found then return null; end if;
  return jsonb_build_object('id', v_uid, 'name', r.name, 'email', r.email, 'role', r.role,
                            'status', coalesce(r.tstatus, r.pstatus), 'teacherId', r.tid, 'teacherCode', r.tcode,
                            'today', private.academy_today());
end $$;

-- Turns the signed-in new account into the FIRST administrator. Needs the one-time setup code.
create or replace function public.claim_first_admin(p_code text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := (select auth.uid());
  v_rows integer;
begin
  if v_uid is null then perform private.fail(401, 'Please sign in to continue.'); end if;
  perform pg_advisory_xact_lock(hashtext('sunshine_first_admin'));
  if exists (select 1 from public.profiles where role = 'admin') then
    perform private.fail(403, 'The administrator account has already been created. Please sign in.');
  end if;
  if not exists (select 1 from private.setup_secret s where s.code = coalesce(p_code, '')) then
    perform private.fail(403, 'The setup code is not correct.', 'setup_code');
  end if;

  perform set_config('app.role_change', 'allowed', true);
  update public.profiles set role = 'admin', status = 'active' where auth_user_id = v_uid;
  get diagnostics v_rows = row_count;
  perform set_config('app.role_change', '', true);      -- close the door again immediately
  if v_rows = 0 then perform private.fail(404, 'We could not find your account.'); end if;

  -- An administrator is not a teacher: remove the pending teacher row the sign-up created (it has no attendance).
  delete from public.teachers t where t.auth_user_id = v_uid
    and not exists (select 1 from public.attendance a where a.teacher_id = t.id);
  delete from private.setup_secret;          -- the code can never be used again
  perform private.audit(v_uid, 'admin_created', 'profile', v_uid::text, null, jsonb_build_object('role', 'admin'));
  return public.my_account();
end $$;

-- An admin can change their own display name (teachers' names are managed by the admin).
create or replace function public.update_my_name(p_name text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_name text := trim(coalesce(p_name, ''));
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if char_length(v_name) not between 2 and 80 then perform private.fail(400, 'Enter your full name.', 'name'); end if;
  update public.profiles set name = v_name where auth_user_id = (select auth.uid());
  return jsonb_build_object('message', 'Profile updated successfully.', 'user', public.my_account());
end $$;

-- 5.2 Teachers -----------------------------------------------------------------------------

create or replace function private.validate_teacher_input(
  p_code text, p_name text, p_phone text, p_subject text, p_dob text, p_joining text, p_address text, p_status text
) returns jsonb language plpgsql stable set search_path = '' as $$
declare
  v_code    text := upper(trim(coalesce(p_code, '')));
  v_name    text := trim(coalesce(p_name, ''));
  v_phone   text := trim(coalesce(p_phone, ''));
  v_subject text := trim(coalesce(p_subject, ''));
  v_address text := trim(coalesce(p_address, ''));
  v_status  text := coalesce(nullif(trim(coalesce(p_status, '')), ''), 'active');
  v_join    date;
  v_dob     date;
  v_dob_txt text := nullif(trim(coalesce(p_dob, '')), '');
begin
  if v_code !~ '^[A-Z0-9-]{2,20}$' then perform private.fail(400, 'Use letters, numbers and dashes only (2–20 characters).', 'teacher_id'); end if;
  if char_length(v_name) not between 2 and 80 then perform private.fail(400, 'Enter the full name.', 'name'); end if;
  if v_phone !~ '^[0-9+()[:space:]-]{7,20}$' then perform private.fail(400, 'Enter a valid phone number.', 'phone'); end if;
  if char_length(v_subject) not between 2 and 60 then perform private.fail(400, 'Enter the subject.', 'subject'); end if;
  begin v_join := nullif(trim(coalesce(p_joining, '')), '')::date; exception when others then v_join := null; end;
  if v_join is null then perform private.fail(400, 'Choose the joining date.', 'joining_date'); end if;
  if v_dob_txt is not null then
    begin v_dob := v_dob_txt::date; exception when others then v_dob := null; end;
    if v_dob is null then perform private.fail(400, 'Enter a valid date of birth.', 'date_of_birth'); end if;
    if v_dob >= v_join then perform private.fail(400, 'Date of birth must be before the joining date.', 'date_of_birth'); end if;
  end if;
  if char_length(v_address) > 200 then perform private.fail(400, 'Address is too long.', 'address'); end if;
  if v_status not in ('active', 'inactive', 'pending', 'rejected') then perform private.fail(400, 'Choose a status.', 'status'); end if;
  return jsonb_build_object('teacher_id', v_code, 'name', v_name, 'phone', v_phone, 'subject', v_subject,
                            'date_of_birth', coalesce(v_dob::text, ''), 'joining_date', v_join::text,
                            'address', v_address, 'status', v_status);
end $$;

create or replace function public.list_teachers(
  p_search text default '', p_status text default '', p_page integer default 1, p_limit integer default 10
) returns jsonb language plpgsql stable security invoker set search_path = '' as $$
declare
  v_page   integer := greatest(coalesce(p_page, 1), 1);
  v_limit  integer := least(greatest(coalesce(p_limit, 10), 1), 100);
  v_search text := trim(coalesce(p_search, ''));
  v_like   text;
  v_status text := case when p_status in ('active', 'inactive', 'pending', 'rejected') then p_status else '' end;
  v_total  integer;
  v_data   jsonb;
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  -- escape LIKE wildcards so "%" and "_" are searched as ordinary characters
  v_like := '%' || replace(replace(replace(v_search, '\', '\\'), '%', '\%'), '_', '\_') || '%';

  select count(*) into v_total from public.teachers t
   where (v_status = '' or t.status = v_status)
     and (v_search = '' or t.name ilike v_like or t.teacher_id ilike v_like or t.subject ilike v_like);

  select coalesce(jsonb_agg(private.teacher_json(x) order by x.teacher_id), '[]'::jsonb) into v_data
    from (select t.* from public.teachers t
           where (v_status = '' or t.status = v_status)
             and (v_search = '' or t.name ilike v_like or t.teacher_id ilike v_like or t.subject ilike v_like)
           order by t.teacher_id limit v_limit offset (v_page - 1) * v_limit) x;

  return jsonb_build_object('data', v_data,
    'pagination', jsonb_build_object('page', v_page, 'limit', v_limit, 'total', v_total, 'pages', greatest(ceil(v_total::numeric / v_limit)::integer, 1)));
end $$;

create or replace function public.teacher_options() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  return jsonb_build_object('data', coalesce((
    select jsonb_agg(jsonb_build_object('id', t.id, 'teacher_id', t.teacher_id, 'name', t.name, 'subject', t.subject, 'status', t.status) order by t.name)
      from public.teachers t), '[]'::jsonb));
end $$;

create or replace function public.teacher_subjects() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  return jsonb_build_object('data', coalesce((
    select jsonb_agg(s order by s) from (select distinct t.subject as s from public.teachers t where t.subject <> '') q), '[]'::jsonb));
end $$;

-- One teacher. Admin: any teacher. Teacher: only themselves (RLS hides the rest).
create or replace function public.get_teacher(p_id bigint) returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare v_t public.teachers;
begin
  select * into v_t from public.teachers t where t.id = p_id;
  if not found then perform private.fail(404, 'We could not find that teacher.'); end if;
  return jsonb_build_object('data', private.teacher_json(v_t));
end $$;

create or replace function public.get_my_teacher() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare v_t public.teachers;
begin
  select * into v_t from public.teachers t where t.auth_user_id = (select auth.uid());
  if not found then perform private.fail(404, 'We could not find your teacher profile.'); end if;
  return jsonb_build_object('data', private.teacher_json(v_t));
end $$;

-- Checks EVERYTHING about a new teacher before the login account is created (so no half-created accounts).
create or replace function public.admin_precheck_new_teacher(
  p_teacher_id text, p_name text, p_email text, p_phone text, p_subject text,
  p_date_of_birth text, p_joining_date text, p_address text, p_status text
) returns boolean language plpgsql security definer set search_path = '' as $$
declare v jsonb; v_email text := lower(trim(coalesce(p_email, '')));
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if v_email !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' or char_length(v_email) > 120 then
    perform private.fail(400, 'Enter a valid email address.', 'email');
  end if;
  v := private.validate_teacher_input(p_teacher_id, p_name, p_phone, p_subject, p_date_of_birth, p_joining_date, p_address, coalesce(nullif(p_status, ''), 'active'));
  if v ->> 'status' not in ('active', 'inactive') then perform private.fail(400, 'Choose a status.', 'status'); end if;
  if exists (select 1 from public.teachers t where t.teacher_id = v ->> 'teacher_id') then
    perform private.fail(409, 'This Teacher ID is already in use.', 'teacher_id');
  end if;
  if exists (select 1 from public.teachers t where lower(t.email) = v_email) or exists (select 1 from auth.users u where lower(u.email) = v_email) then
    perform private.fail(409, 'This email is already in use.', 'email');
  end if;
  return true;
end $$;

-- Edit a teacher (email is the login, so it cannot be changed here).
create or replace function public.admin_update_teacher(
  p_id bigint, p_teacher_id text, p_name text, p_phone text, p_subject text,
  p_date_of_birth text, p_joining_date text, p_address text, p_status text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v jsonb; v_t public.teachers;
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  v := private.validate_teacher_input(p_teacher_id, p_name, p_phone, p_subject, p_date_of_birth, p_joining_date, p_address, p_status);
  begin
    update public.teachers set
      teacher_id = v ->> 'teacher_id', name = v ->> 'name', phone = v ->> 'phone', subject = v ->> 'subject',
      date_of_birth = nullif(v ->> 'date_of_birth', '')::date, joining_date = (v ->> 'joining_date')::date,
      address = v ->> 'address', status = v ->> 'status'
    where id = p_id returning * into v_t;
  exception when unique_violation then
    perform private.fail(409, 'This Teacher ID is already in use.', 'teacher_id');
  end;
  if v_t.id is null then perform private.fail(404, 'We could not find that teacher.'); end if;
  return jsonb_build_object('message', 'Teacher updated successfully.', 'data', private.teacher_json(v_t));
end $$;

-- Approve / reject / activate / deactivate. History is always kept.
create or replace function public.admin_set_teacher_status(p_id bigint, p_status text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_old text; v_t public.teachers; v_msg text;
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if p_status not in ('active', 'inactive', 'rejected') then perform private.fail(400, 'Choose a status.', 'status'); end if;
  select status into v_old from public.teachers where id = p_id for update;
  if not found then perform private.fail(404, 'We could not find that teacher.'); end if;
  update public.teachers set status = p_status where id = p_id returning * into v_t;
  v_msg := case p_status
    when 'active'   then case when v_old = 'pending' then 'Teacher approved successfully.' else 'Teacher activated successfully.' end
    when 'inactive' then 'Teacher deactivated successfully.'
    else 'Registration rejected.' end;
  return jsonb_build_object('message', v_msg, 'data', private.teacher_json(v_t));
end $$;

-- Second half of "Add Teacher": the new login already exists (and arrived as pending); fill in the record and activate it.
create or replace function public.admin_complete_new_teacher(
  p_auth_user_id uuid, p_teacher_id text, p_name text, p_phone text, p_subject text,
  p_date_of_birth text, p_joining_date text, p_address text, p_status text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v jsonb; v_t public.teachers; v_id bigint;
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  v := private.validate_teacher_input(p_teacher_id, p_name, p_phone, p_subject, p_date_of_birth, p_joining_date, p_address, coalesce(nullif(p_status, ''), 'active'));
  if v ->> 'status' not in ('active', 'inactive') then perform private.fail(400, 'Choose a status.', 'status'); end if;
  select id into v_id from public.teachers where auth_user_id = p_auth_user_id and status = 'pending' for update;
  if v_id is null then perform private.fail(409, 'We could not finish creating this teacher. Please check the Teachers page.'); end if;
  begin
    update public.teachers set
      teacher_id = v ->> 'teacher_id', name = v ->> 'name', phone = v ->> 'phone', subject = v ->> 'subject',
      date_of_birth = nullif(v ->> 'date_of_birth', '')::date, joining_date = (v ->> 'joining_date')::date,
      address = v ->> 'address', status = v ->> 'status'
    where id = v_id returning * into v_t;
  exception when unique_violation then
    perform private.fail(409, 'This Teacher ID is already in use.', 'teacher_id');
  end;
  return jsonb_build_object('message', 'Teacher added successfully.', 'data', private.teacher_json(v_t));
end $$;

-- 5.3 Attendance: reading -------------------------------------------------------------------

-- The "Mark Attendance" sheet for one date (default: today by the academy clock): every active teacher + their record.
create or replace function public.get_attendance_sheet(p_date date default null) returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare v_date date := coalesce(p_date, private.academy_today());
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if v_date > private.academy_today() then perform private.fail(400, 'You cannot mark attendance for a future date.', 'date'); end if;
  return jsonb_build_object('date', to_char(v_date, 'YYYY-MM-DD'), 'data', coalesce((
    select jsonb_agg(jsonb_build_object(
             'teacher', private.teacher_json(t),
             'attendance', case when a.id is null then null else private.att_json(a, t) end) order by t.name)
      from public.teachers t
      left join public.attendance a on a.teacher_id = t.id and a.attendance_date = v_date
     where t.status = 'active'), '[]'::jsonb));
end $$;

-- Paginated history with filters. A teacher always gets only their own rows (also enforced by RLS).
create or replace function public.list_attendance(
  p_teacher bigint default null, p_subject text default '', p_status text default '',
  p_date date default null, p_from date default null, p_to date default null,
  p_page integer default 1, p_limit integer default 10
) returns jsonb language plpgsql stable security invoker set search_path = '' as $$
declare
  v_admin   boolean := private.is_admin();
  v_teacher bigint  := p_teacher;
  v_page    integer := greatest(coalesce(p_page, 1), 1);
  v_limit   integer := least(greatest(coalesce(p_limit, 10), 1), 100);
  v_status  text    := case when p_status in ('present', 'absent', 'late', 'leave') then p_status else '' end;
  v_subject text    := coalesce(p_subject, '');
  v_total   integer;
  v_data    jsonb;
begin
  if not v_admin then
    v_teacher := private.current_teacher_id();
    if v_teacher is null then perform private.fail(403, 'Your account is not active.'); end if;
  end if;

  select count(*) into v_total
    from public.attendance a join public.teachers t on t.id = a.teacher_id
   where (v_teacher is null or a.teacher_id = v_teacher) and (v_subject = '' or t.subject = v_subject)
     and (v_status = '' or a.status = v_status) and (p_date is null or a.attendance_date = p_date)
     and (p_date is not null or p_from is null or a.attendance_date >= p_from)
     and (p_date is not null or p_to is null or a.attendance_date <= p_to);

  select coalesce(jsonb_agg(private.att_json(q.a, q.t) order by q.d desc, q.i desc), '[]'::jsonb) into v_data
    from (select a as a, t as t, a.attendance_date as d, a.id as i
            from public.attendance a join public.teachers t on t.id = a.teacher_id
           where (v_teacher is null or a.teacher_id = v_teacher) and (v_subject = '' or t.subject = v_subject)
             and (v_status = '' or a.status = v_status) and (p_date is null or a.attendance_date = p_date)
             and (p_date is not null or p_from is null or a.attendance_date >= p_from)
             and (p_date is not null or p_to is null or a.attendance_date <= p_to)
           order by a.attendance_date desc, a.id desc limit v_limit offset (v_page - 1) * v_limit) q;

  return jsonb_build_object('data', v_data,
    'pagination', jsonb_build_object('page', v_page, 'limit', v_limit, 'total', v_total, 'pages', greatest(ceil(v_total::numeric / v_limit)::integer, 1)));
end $$;

-- Totals + attendance % for one teacher (a teacher always gets their own).
create or replace function public.attendance_summary(p_teacher bigint default null, p_from date default null, p_to date default null) returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare v_teacher bigint := p_teacher; r record;
begin
  if not private.is_admin() then
    v_teacher := private.current_teacher_id();
    if v_teacher is null then perform private.fail(403, 'Your account is not active.'); end if;
  elsif v_teacher is null then
    perform private.fail(400, 'Choose a teacher first.');
  end if;
  select count(*) filter (where status = 'present') as p, count(*) filter (where status = 'absent') as a,
         count(*) filter (where status = 'late') as l, count(*) filter (where status = 'leave') as v
    into r from public.attendance
   where teacher_id = v_teacher and (p_from is null or attendance_date >= p_from) and (p_to is null or attendance_date <= p_to);
  return private.stats_json(r.p::integer, r.a::integer, r.l::integer, r.v::integer);
end $$;

-- Monthly / date-range report: one row per teacher + academy totals.
create or replace function public.attendance_report(p_teacher bigint default null, p_from date default null, p_to date default null) returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare v_rows jsonb; tp integer; ta integer; tl integer; tv integer;
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  with agg as (
    select t.id, t.teacher_id as code, t.name, t.subject,
           (count(*) filter (where x.status = 'present'))::integer as p, (count(*) filter (where x.status = 'absent'))::integer as a,
           (count(*) filter (where x.status = 'late'))::integer as l, (count(*) filter (where x.status = 'leave'))::integer as v
      from public.attendance x join public.teachers t on t.id = x.teacher_id
     where (p_teacher is null or t.id = p_teacher) and (p_from is null or x.attendance_date >= p_from) and (p_to is null or x.attendance_date <= p_to)
     group by t.id, t.teacher_id, t.name, t.subject)
  select coalesce(jsonb_agg(jsonb_build_object('teacher', jsonb_build_object('id', id, 'teacher_id', code, 'name', name, 'subject', subject)) || private.stats_json(p, a, l, v) order by name), '[]'::jsonb),
         coalesce(sum(p), 0)::integer, coalesce(sum(a), 0)::integer, coalesce(sum(l), 0)::integer, coalesce(sum(v), 0)::integer
    into v_rows, tp, ta, tl, tv from agg;
  return jsonb_build_object('period', jsonb_build_object('from', p_from, 'to', p_to), 'totals', private.stats_json(tp, ta, tl, tv), 'rows', v_rows);
end $$;

-- Yearly report: January..December totals, plus a per-teacher total for the year. Past years stay available.
create or replace function public.attendance_yearly_report(p_year integer, p_teacher bigint default null) returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare v_from date; v_to date; v_months jsonb; v_teachers jsonb; v_tot record;
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if p_year is null or p_year not between 2000 and 2100 then perform private.fail(400, 'Choose a valid year.', 'year'); end if;
  v_from := make_date(p_year, 1, 1); v_to := make_date(p_year, 12, 31);

  select coalesce(jsonb_agg(jsonb_build_object('month', m.n) || private.stats_json(coalesce(c.p, 0), coalesce(c.a, 0), coalesce(c.l, 0), coalesce(c.v, 0)) order by m.n), '[]'::jsonb)
    into v_months
    from generate_series(1, 12) as m(n)
    left join (select extract(month from x.attendance_date)::integer as mn,
                      (count(*) filter (where x.status = 'present'))::integer as p, (count(*) filter (where x.status = 'absent'))::integer as a,
                      (count(*) filter (where x.status = 'late'))::integer as l, (count(*) filter (where x.status = 'leave'))::integer as v
                 from public.attendance x
                where x.attendance_date between v_from and v_to and (p_teacher is null or x.teacher_id = p_teacher)
                group by 1) c on c.mn = m.n;

  select coalesce(jsonb_agg(jsonb_build_object('teacher', jsonb_build_object('id', q.id, 'teacher_id', q.code, 'name', q.name, 'subject', q.subject)) || private.stats_json(q.p, q.a, q.l, q.v) order by q.name), '[]'::jsonb)
    into v_teachers
    from (select t.id, t.teacher_id as code, t.name, t.subject,
                 (count(*) filter (where x.status = 'present'))::integer as p, (count(*) filter (where x.status = 'absent'))::integer as a,
                 (count(*) filter (where x.status = 'late'))::integer as l, (count(*) filter (where x.status = 'leave'))::integer as v
            from public.attendance x join public.teachers t on t.id = x.teacher_id
           where x.attendance_date between v_from and v_to and (p_teacher is null or t.id = p_teacher)
           group by t.id, t.teacher_id, t.name, t.subject) q;

  select count(*) filter (where x.status = 'present') as p, count(*) filter (where x.status = 'absent') as a,
         count(*) filter (where x.status = 'late') as l, count(*) filter (where x.status = 'leave') as v
    into v_tot from public.attendance x
   where x.attendance_date between v_from and v_to and (p_teacher is null or x.teacher_id = p_teacher);

  return jsonb_build_object('year', p_year, 'months', v_months, 'teachers', v_teachers,
                            'totals', private.stats_json(v_tot.p::integer, v_tot.a::integer, v_tot.l::integer, v_tot.v::integer));
end $$;

create or replace function public.dashboard_admin() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare v_today date := private.academy_today(); v_total integer; v_pending integer; v_marked_active integer; v_list jsonb; r record;
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  select count(*) into v_total from public.teachers where status = 'active';
  select count(*) into v_pending from public.teachers where status = 'pending';
  select count(*) filter (where a.status = 'present') as p, count(*) filter (where a.status = 'absent') as a,
         count(*) filter (where a.status = 'late') as l, count(*) filter (where a.status = 'leave') as v,
         count(*) filter (where t.status = 'active') as marked
    into r from public.attendance a join public.teachers t on t.id = a.teacher_id where a.attendance_date = v_today;
  v_marked_active := r.marked;
  select coalesce(jsonb_agg(private.att_json(a, t) order by t.name), '[]'::jsonb) into v_list
    from public.attendance a join public.teachers t on t.id = a.teacher_id where a.attendance_date = v_today;
  return jsonb_build_object('date', to_char(v_today, 'YYYY-MM-DD'),
    'stats', jsonb_build_object('totalTeachers', v_total, 'present', r.p, 'absent', r.a, 'late', r.l, 'leave', r.v,
                                'notMarked', greatest(v_total - v_marked_active, 0), 'pending', v_pending),
    'todayAttendance', v_list);
end $$;

create or replace function public.dashboard_teacher() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare
  v_tid bigint := private.current_teacher_id(); v_today date := private.academy_today();
  v_month date := date_trunc('month', private.academy_today())::date;
  o record; m record; v_today_rec jsonb; v_recent jsonb;
begin
  if v_tid is null then perform private.fail(403, 'Your account is not active.'); end if;
  select count(*) filter (where status = 'present') as p, count(*) filter (where status = 'absent') as a,
         count(*) filter (where status = 'late') as l, count(*) filter (where status = 'leave') as v,
         count(*) filter (where status = 'present' and attendance_date >= v_month) as mp, count(*) filter (where status = 'absent' and attendance_date >= v_month) as ma,
         count(*) filter (where status = 'late' and attendance_date >= v_month) as ml, count(*) filter (where status = 'leave' and attendance_date >= v_month) as mv
    into o from public.attendance where teacher_id = v_tid;
  select private.att_json(a, t) into v_today_rec from public.attendance a join public.teachers t on t.id = a.teacher_id
   where a.teacher_id = v_tid and a.attendance_date = v_today;
  select coalesce(jsonb_agg(private.att_json(q.a, q.t) order by q.d desc), '[]'::jsonb) into v_recent
    from (select a as a, t as t, a.attendance_date as d from public.attendance a join public.teachers t on t.id = a.teacher_id
           where a.teacher_id = v_tid order by a.attendance_date desc limit 7) q;
  return jsonb_build_object('date', to_char(v_today, 'YYYY-MM-DD'),
    'overall', private.stats_json(o.p::integer, o.a::integer, o.l::integer, o.v::integer),
    'thisMonth', private.stats_json(o.mp::integer, o.ma::integer, o.ml::integer, o.mv::integer),
    'today', v_today_rec, 'recent', v_recent, 'rules', private.rules_json());
end $$;

-- 5.4 Attendance: writing -------------------------------------------------------------------

-- A teacher checks in. The date and time come from the DATABASE clock (academy timezone), never from the browser.
create or replace function public.self_check_in() returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_tid bigint := private.current_teacher_id();
  v_now timestamp := private.academy_now();
  v_today date := v_now::date;
  v_time time := date_trunc('minute', v_now)::time;
  v_ex public.attendance; v_status text; v_row public.attendance; v_t public.teachers;
begin
  if (select auth.uid()) is null then perform private.fail(401, 'Please sign in to continue.'); end if;
  if v_tid is null then perform private.fail(403, 'Your account is not active.'); end if;
  if private.setting('self_checkin', '1') <> '1' then
    perform private.fail(403, 'Self check-in is turned off. Please ask the administrator to mark your attendance.');
  end if;
  select * into v_ex from public.attendance where teacher_id = v_tid and attendance_date = v_today;
  if found then
    perform private.fail(409, case when v_ex.check_in is not null then 'You have already checked in today.'
                                   else 'Your attendance for today has already been marked by the administrator.' end);
  end if;
  v_status := case when private.minutes_of(v_time) > private.on_time_limit() then 'late' else 'present' end;
  begin
    insert into public.attendance (teacher_id, attendance_date, check_in, status, remarks)
    values (v_tid, v_today, v_time, v_status, 'Self check-in') returning * into v_row;
  exception when unique_violation then
    perform private.fail(409, 'You have already checked in today.');
  end;
  select * into v_t from public.teachers where id = v_tid;
  return jsonb_build_object(
    'message', case when v_status = 'late'
        then format('Checked in at %s. You are marked Late (%s minutes after %s).', to_char(v_time, 'FMHH12:MI AM'), v_row.late_minutes, to_char(private.setting('school_start', '08:00')::time, 'FMHH12:MI AM'))
        else format('Checked in at %s. You are marked Present.', to_char(v_time, 'FMHH12:MI AM')) end,
    'data', private.att_json(v_row, v_t));
end $$;

create or replace function public.self_check_out() returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_tid bigint := private.current_teacher_id();
  v_now timestamp := private.academy_now();
  v_time time := date_trunc('minute', v_now)::time;
  v_rec public.attendance; v_t public.teachers;
begin
  if (select auth.uid()) is null then perform private.fail(401, 'Please sign in to continue.'); end if;
  if v_tid is null then perform private.fail(403, 'Your account is not active.'); end if;
  if private.setting('self_checkin', '1') <> '1' then
    perform private.fail(403, 'Self check-in is turned off. Please ask the administrator to mark your attendance.');
  end if;
  select * into v_rec from public.attendance where teacher_id = v_tid and attendance_date = v_now::date for update;
  if not found then perform private.fail(409, 'Please check in first.'); end if;
  if v_rec.status in ('absent', 'leave') then perform private.fail(409, 'Your attendance for today was marked by the administrator.'); end if;
  if v_rec.check_in is null then perform private.fail(409, 'Please check in first.'); end if;
  if v_rec.check_out is not null then perform private.fail(409, 'You have already checked out today.'); end if;
  if v_time <= v_rec.check_in then perform private.fail(409, 'Please wait a minute before checking out.'); end if;
  update public.attendance set check_out = v_time where id = v_rec.id returning * into v_rec;
  select * into v_t from public.teachers where id = v_tid;
  return jsonb_build_object('message', 'Checked out at ' || to_char(v_time, 'FMHH12:MI AM') || '. Have a good day!', 'data', private.att_json(v_rec, v_t));
end $$;

-- Clean "HH:MM" text -> time (empty -> NULL). Raises a friendly error otherwise.
create or replace function private.parse_time(p_text text, p_hint text) returns time
language plpgsql immutable set search_path = '' as $$
begin
  if coalesce(trim(p_text), '') = '' then return null; end if;
  if trim(p_text) !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then perform private.fail(400, 'Enter the time as HH:MM.', p_hint); end if;
  return trim(p_text)::time;
end $$;

-- Admin saves many records for one date. Re-saving never duplicates (unique teacher + date).
create or replace function public.admin_save_attendance(p_date date, p_records jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_rec jsonb; v_i integer := 0; v_saved integer := 0;
  v_tid bigint; v_status text; v_in time; v_out time; v_remarks text;
  v_old public.attendance; v_new public.attendance; v_uid uuid := (select auth.uid());
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if p_date is null then perform private.fail(400, 'Enter a valid date.', 'date'); end if;
  if p_date > private.academy_today() then perform private.fail(400, 'You cannot mark attendance for a future date.', 'date'); end if;
  if p_records is null or jsonb_typeof(p_records) <> 'array' or jsonb_array_length(p_records) = 0 or jsonb_array_length(p_records) > 500 then
    perform private.fail(400, 'There are no teachers to save.');
  end if;

  for v_rec in select * from jsonb_array_elements(p_records) loop
    begin v_tid := (v_rec ->> 'teacher')::bigint; exception when others then v_tid := null; end;
    v_status := v_rec ->> 'status';
    if v_tid is null then perform private.fail(400, 'Invalid teacher.'); end if;
    if v_status is null or v_status not in ('present', 'absent', 'late', 'leave') then perform private.fail(400, 'Choose a status.', 'records.' || v_i || '.status'); end if;
    v_remarks := left(trim(coalesce(v_rec ->> 'remarks', '')), 201);
    if char_length(v_remarks) > 200 then perform private.fail(400, 'Remarks are too long (200 characters max).', 'records.' || v_i || '.remarks'); end if;
    v_in  := private.parse_time(v_rec ->> 'check_in',  'records.' || v_i || '.check_in');
    v_out := private.parse_time(v_rec ->> 'check_out', 'records.' || v_i || '.check_out');
    if v_status in ('absent', 'leave') then v_in := null; v_out := null; end if;
    if v_in is not null and v_out is not null and v_out <= v_in then perform private.fail(400, 'Check-out must be after check-in.', 'records.' || v_i || '.check_out'); end if;
    if not exists (select 1 from public.teachers t where t.id = v_tid and t.status = 'active') then
      perform private.fail(400, 'Some teachers could not be found or are inactive. Please refresh and try again.');
    end if;

    select * into v_old from public.attendance where teacher_id = v_tid and attendance_date = p_date for update;
    if not found then
      insert into public.attendance (teacher_id, attendance_date, check_in, check_out, status, remarks, created_by, updated_by)
      values (v_tid, p_date, v_in, v_out, v_status, v_remarks, v_uid, v_uid) returning * into v_new;
      perform private.audit(v_uid, 'attendance_created', 'attendance', v_new.id::text, null,
        jsonb_build_object('teacher_id', v_tid, 'date', p_date, 'status', v_status, 'check_in', v_in, 'check_out', v_out, 'remarks', v_remarks));
    elsif (v_old.status, v_old.check_in, v_old.check_out, v_old.remarks) is distinct from (v_status, v_in, v_out, v_remarks) then
      update public.attendance set status = v_status, check_in = v_in, check_out = v_out, remarks = v_remarks, updated_by = v_uid
       where id = v_old.id returning * into v_new;
      perform private.audit(v_uid, 'attendance_edited', 'attendance', v_new.id::text,
        jsonb_build_object('status', v_old.status, 'check_in', v_old.check_in, 'check_out', v_old.check_out, 'remarks', v_old.remarks),
        jsonb_build_object('status', v_status, 'check_in', v_in, 'check_out', v_out, 'remarks', v_remarks));
    end if;
    v_saved := v_saved + 1; v_i := v_i + 1;
  end loop;
  return jsonb_build_object('message', 'Attendance saved successfully.', 'saved', v_saved);
end $$;

-- Admin corrects one record (teacher and date cannot change).
create or replace function public.admin_update_attendance(p_id bigint, p_status text, p_check_in text, p_check_out text, p_remarks text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_old public.attendance; v_new public.attendance; v_t public.teachers; v_uid uuid := (select auth.uid());
  v_in time; v_out time; v_remarks text := trim(coalesce(p_remarks, ''));
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if p_status is null or p_status not in ('present', 'absent', 'late', 'leave') then perform private.fail(400, 'Choose a status.', 'status'); end if;
  if char_length(v_remarks) > 200 then perform private.fail(400, 'Remarks are too long (200 characters max).', 'remarks'); end if;
  v_in := private.parse_time(p_check_in, 'check_in'); v_out := private.parse_time(p_check_out, 'check_out');
  if p_status in ('absent', 'leave') then v_in := null; v_out := null; end if;
  if v_in is not null and v_out is not null and v_out <= v_in then perform private.fail(400, 'Check-out must be after check-in.', 'check_out'); end if;
  select * into v_old from public.attendance where id = p_id for update;
  if not found then perform private.fail(404, 'We could not find that attendance record.'); end if;
  update public.attendance set status = p_status, check_in = v_in, check_out = v_out, remarks = v_remarks, updated_by = v_uid
   where id = p_id returning * into v_new;
  if (v_old.status, v_old.check_in, v_old.check_out, v_old.remarks) is distinct from (v_new.status, v_new.check_in, v_new.check_out, v_new.remarks) then
    perform private.audit(v_uid, 'attendance_edited', 'attendance', p_id::text,
      jsonb_build_object('status', v_old.status, 'check_in', v_old.check_in, 'check_out', v_old.check_out, 'remarks', v_old.remarks),
      jsonb_build_object('status', v_new.status, 'check_in', v_new.check_in, 'check_out', v_new.check_out, 'remarks', v_new.remarks));
  end if;
  select * into v_t from public.teachers where id = v_new.teacher_id;
  return jsonb_build_object('message', 'Attendance updated successfully.', 'data', private.att_json(v_new, v_t));
end $$;

-- 5.5 Settings ------------------------------------------------------------------------------

create or replace function public.get_settings() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  return jsonb_build_object('data', private.rules_json());
end $$;

create or replace function public.admin_update_settings(p_start_time text, p_grace_minutes integer, p_self_checkin boolean) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_uid uuid := (select auth.uid());
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  if coalesce(p_start_time, '') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then perform private.fail(400, 'Choose the time school starts.', 'startTime'); end if;
  if p_grace_minutes is null or p_grace_minutes not between 0 and 120 then perform private.fail(400, 'Enter a whole number of minutes (0–120).', 'graceMinutes'); end if;
  insert into public.settings (name, value, updated_by) values ('school_start', p_start_time, v_uid)
    on conflict (name) do update set value = excluded.value, updated_by = excluded.updated_by;
  insert into public.settings (name, value, updated_by) values ('grace_minutes', p_grace_minutes::text, v_uid)
    on conflict (name) do update set value = excluded.value, updated_by = excluded.updated_by;
  insert into public.settings (name, value, updated_by) values ('self_checkin', case when coalesce(p_self_checkin, false) then '1' else '0' end, v_uid)
    on conflict (name) do update set value = excluded.value, updated_by = excluded.updated_by;
  return jsonb_build_object('message', 'Settings saved successfully.', 'data', private.rules_json());
end $$;

-- 5.6 Backup / archive exports (admin only; paged so large years still work) ---------------------

create or replace function public.admin_export_attendance(p_after_id bigint default 0, p_limit integer default 1000, p_from date default null, p_to date default null) returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', q.id, 'teacher_id', q.code, 'teacher_name', q.name, 'subject', q.subject, 'date', to_char(q.d, 'YYYY-MM-DD'),
      'check_in', coalesce(to_char(q.ci, 'HH24:MI'), ''), 'check_out', coalesce(to_char(q.co, 'HH24:MI'), ''),
      'status', q.status, 'late_minutes', q.late, 'remarks', q.remarks) order by q.id)
    from (select a.id, t.teacher_id as code, t.name, t.subject, a.attendance_date as d, a.check_in as ci, a.check_out as co, a.status, a.late_minutes as late, a.remarks
            from public.attendance a join public.teachers t on t.id = a.teacher_id
           where a.id > coalesce(p_after_id, 0) and (p_from is null or a.attendance_date >= p_from) and (p_to is null or a.attendance_date <= p_to)
           order by a.id limit least(greatest(coalesce(p_limit, 1000), 1), 2000)) q), '[]'::jsonb);
end $$;

create or replace function public.admin_export_teachers() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
begin
  if not private.is_admin() then perform private.fail(403, 'You don''t have permission to do that.'); end if;
  return coalesce((select jsonb_agg(private.teacher_json(t) order by t.teacher_id) from public.teachers t), '[]'::jsonb);
end $$;

-- ---------- 6. Who may call what -------------------------------------------------------------
-- By default Postgres lets everyone run every function. Close that, then open only what is needed.
revoke all on all functions in schema public  from public, anon, authenticated;
revoke all on all functions in schema private from public, anon, authenticated;

-- Before sign-in (anonymous): only these two harmless checks.
grant execute on function public.needs_setup()              to anon, authenticated;
grant execute on function public.verify_setup_code(text)    to anon, authenticated;

-- Signed-in users. Each function still checks the caller's role/status itself.
grant execute on function
  public.my_account(),
  public.claim_first_admin(text),
  public.update_my_name(text),
  public.list_teachers(text, text, integer, integer),
  public.teacher_options(),
  public.teacher_subjects(),
  public.get_teacher(bigint),
  public.get_my_teacher(),
  public.admin_precheck_new_teacher(text, text, text, text, text, text, text, text, text),
  public.admin_update_teacher(bigint, text, text, text, text, text, text, text, text),
  public.admin_set_teacher_status(bigint, text),
  public.admin_complete_new_teacher(uuid, text, text, text, text, text, text, text, text),
  public.get_attendance_sheet(date),
  public.list_attendance(bigint, text, text, date, date, date, integer, integer),
  public.attendance_summary(bigint, date, date),
  public.attendance_report(bigint, date, date),
  public.attendance_yearly_report(integer, bigint),
  public.dashboard_admin(),
  public.dashboard_teacher(),
  public.self_check_in(),
  public.self_check_out(),
  public.admin_save_attendance(date, jsonb),
  public.admin_update_attendance(bigint, text, text, text, text),
  public.get_settings(),
  public.admin_update_settings(text, integer, boolean),
  public.admin_export_attendance(bigint, integer, date, date),
  public.admin_export_teachers()
to authenticated;

-- Internal helpers that policies and "run as caller" functions need. (Not callable through the API: schema "private" is not exposed.)
grant execute on function
  private.is_admin(), private.current_teacher_id(), private.academy_today(), private.academy_now(),
  private.rules_json(), private.fail(integer, text, text), private.teacher_json(public.teachers),
  private.att_json(public.attendance, public.teachers), private.stats_json(integer, integer, integer, integer)
to authenticated;

-- ---------- 7. Default settings and the one-time setup code ---------------------------------
insert into public.settings (name, value) values
  ('school_start', '08:00'), ('grace_minutes', '15'), ('self_checkin', '1'),
  ('timezone', 'Asia/Karachi'), ('max_pending', '25'), ('legacy_link', '0')
on conflict (name) do nothing;

-- The code you type on the "Create the administrator account" page (only while no admin exists).
insert into private.setup_secret (code)
select replace(gen_random_uuid()::text, '-', '')
where not exists (select 1 from private.setup_secret) and not exists (select 1 from public.profiles where role = 'admin');

notify pgrst, 'reload schema';

-- Last result shown in the editor = your setup code. Keep it private; it stops working after the admin is created.
select code as "SETUP CODE (keep private)" from private.setup_secret;
